### ISSUE TITLE
Executing 'brew install swarm-clef' results in an error

### ISSUE THREAD

**Issue by nagysandorantal** [ethersphere/homebrew-tap#4]
(base) / » brew install swarm-clef                                                                       
==> Downloading https://formulae.brew.sh/api/formula.jws.json
########################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
########################################################################################################################################################################### 100.0%
Error: swarm-clef: Calling plist_options is disabled! Use service.require_root instead.
Please report this issue to the ethersphere/tap tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/ethersphere/homebrew-tap/swarm-clef.rb:53

https://github.com/ethersphere/homebrew-tap/blob/b82adc019fdca9537c906d6e168508fc78cc3f2c/swarm-clef.rb#L53C11-L53C11

**Comment by vandot** [comment]
@nagysandorantal "fixed it" https://github.com/ethersphere/homebrew-tap/pull/6
